service: rn-sls-message-api
plugins:
  - serverless-webpack
  - serverless-offline
package:
  individually: true
provider:
  name: aws
  runtime: nodejs12.x
  versionFunctions: false
  stage: ${opt:stage, 'dev'}
  region: ${file(config/env/${self:provider.stage}.yml):region}
  environment:
    ENV_NAME: ${self:provider.stage}
custom:
  webpack:
    includeModules: false
  serverless-offline:
    useChildProcesses: true
    allowCache: true

functions: ${file(config/functions.yml)}
#resources: ${file(config/resources.yml)}
#stepFunctions: ${file(config/step-functions.yml)}
