get:
  handler: handlers/message.get
  events:
    - http:
        path: /message/{id}
        method: get
        request:
          parameters:
            paths:
              id: true

post:
  handler: handlers/message.post
  events:
    - http:
        path: /message
        method: post

graphql:
  handler: handlers/graphql.graphqlHandler
  events:
    - http:
        path: graphql
        method: post
    - http:
        path: graphql
        method: get
