get:
  handler: handlers/message.get
  environment:
    RN_TEST: "testing an env variable"
  events:
    - http:
        path: /message/{id}
        method: get
        request:
          parameters:
            paths:
              id: true

post:
  handler: handlers/message.post
  events:
    - http:
        path: /message
        method: post
