#!/bin/bash

docker-compose down --remove-orphans

docker-compose up -d

sleep 10
docker-compose exec -T couchbase couchbase-cli cluster-init --cluster-username admin --cluster-password password --services="data,index,query"
docker-compose exec -T couchbase couchbase-cli bucket-create -c localhost -u admin -p password --enable-flush 1 --bucket-type couchbase --bucket relay_data --bucket-ramsize 100 
sleep 10
docker-compose exec -T couchbase cbq -e "http://127.0.0.1:8091" -u=admin -p=password --script="create primary index on \`relay_data\`"
